import './components/sliders'
import './components/animPlaceholder'
import './components/iMask'
import './components/contactTabs'
import './components/dropzone'
import './components/langSwitch'
import './components/customSelect'
import './components/cutString'
