import './components/sliders'
import './components/animPlaceholder'
import './components/inputMask'
import './components/contactTabs'
import './components/dropzone'
import './components/langSwitch'
import './components/customSelect'
